http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
db_connection:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
nats_server:
  url: "nats://127.0.0.1:4222"